In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [2]:
def chi_square(X, Y):
    return (np.sum(((X-Y)**2)/(X+Y+1)))

# Iris Data

In [3]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv("C:\\Users\\Areeka Aijaz\\Desktop\\Lab 4\\Iris\\iris.data", names=names)

In [4]:
array = dataset.values
X = array[:,0:4]
Y = array[:,4]
t_size = 0.20
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size, random_state=seed)

In [5]:
knn = KNeighborsClassifier(n_neighbors=3, metric=chi_square) 
knn.fit(X_train, Y_train) 
predictions = knn.predict(X_test) 
print("Accuracy Score: ",accuracy_score(Y_test, predictions)) 
print("\nConfusion Matrix\n",confusion_matrix(Y_test, predictions)) 
print("\nClassification Report\n",classification_report(Y_test, predictions))

Accuracy Score:  0.9

Confusion Matrix
 [[ 7  0  0]
 [ 0 10  2]
 [ 0  1 10]]

Classification Report
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.91      0.83      0.87        12
 Iris-virginica       0.83      0.91      0.87        11

      micro avg       0.90      0.90      0.90        30
      macro avg       0.91      0.91      0.91        30
   weighted avg       0.90      0.90      0.90        30



In [6]:
#dis = knn.kneighbors(X=X_train, n_neighbors=3, return_distance=True)
#for i in range(20):
#    print(dis[0][i], dis[1][i])

# Occupency Detection Data

In [7]:
# Read Training Set
trainingset = pd.read_csv("C:\\Users\\Areeka Aijaz\\Desktop\\Lab 4\\Occupency_Detection\\datatraining.txt")

X_train = trainingset.iloc[:, 1:-1]
Y_train = trainingset.iloc[:,-1:].values.ravel()

# Read Testing Set 1
testingset1 = pd.read_csv("C:\\Users\\Areeka Aijaz\\Desktop\\Lab 4\\Occupency_Detection\\datatest.txt")

X_test1 = testingset1.iloc[:, 1:-1]
Y_test1 = testingset1.iloc[:,-1:].values.ravel()

# Read Testing Set 2
testingset2 = pd.read_csv("C:\\Users\\Areeka Aijaz\\Desktop\\Lab 4\\Occupency_Detection\\datatest2.txt")

X_test2 = testingset2.iloc[:, 1:-1]
Y_test2 = testingset2.iloc[:,-1:].values.ravel()

In [8]:
#np.seterr(divide='ignore', invalid='ignore')
knn = KNeighborsClassifier(n_neighbors=3, metric=chi_square) 
knn.fit(X_train, Y_train) 

print("------Test Set 1---------")

predictions = knn.predict(X_test1) 
print("Accuracy Score: ", round(accuracy_score(Y_test1, predictions), 2)) 
print("\nConfusion Matrix\n",confusion_matrix(Y_test1, predictions)) 
print("\nClassification Report\n",classification_report(Y_test1, predictions))

------Test Set 1---------
Accuracy Score:  0.92

Confusion Matrix
 [[1648   45]
 [ 157  815]]

Classification Report
               precision    recall  f1-score   support

           0       0.91      0.97      0.94      1693
           1       0.95      0.84      0.89       972

   micro avg       0.92      0.92      0.92      2665
   macro avg       0.93      0.91      0.92      2665
weighted avg       0.93      0.92      0.92      2665



In [9]:
knn = KNeighborsClassifier(n_neighbors=3, metric=chi_square) 
knn.fit(X_train, Y_train) 

print("------Test Set 2---------")

predictions = knn.predict(X_test2) 
print("Accuracy Score: ", round(accuracy_score(Y_test2, predictions), 2)) 
print("\nConfusion Matrix\n",confusion_matrix(Y_test2, predictions)) 
print("\nClassification Report\n",classification_report(Y_test2, predictions))

------Test Set 2---------
Accuracy Score:  0.96

Confusion Matrix
 [[7385  318]
 [ 111 1938]]

Classification Report
               precision    recall  f1-score   support

           0       0.99      0.96      0.97      7703
           1       0.86      0.95      0.90      2049

   micro avg       0.96      0.96      0.96      9752
   macro avg       0.92      0.95      0.94      9752
weighted avg       0.96      0.96      0.96      9752

